server:
  port: 24550
spring:
  application:
    name: ma-git-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MSunFlower1014/spring-cloud-config/     # 配置git仓库的地址
          search-paths: /                           # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 710131634@qq.com                                            # git仓库的账号
          password: mayantao110                                             # git仓库的密码